<?php
$in = array('🐺',' ','&nbsp;',' ','â€®','ï€€',';-)','XD',':|',':(',':O',':P',':D',':raeg:',':megusta:',':lol:',':troll:','R:',':@',':)','R(',':S','RB:','B)',':pface:',':fp:',':no:',':ohplz:',':ydsay:',':yuno:','&lt;3',';(',':falone:',':ok:',':accept:',':excited:',':stopityou:',':hellno:',':ohgodwhy:',':genius:',':cguy:',':yes:',':gtfo:','-_-',':*',':donut:',':catluv:',':omgrun:');
$out = array(
' ',
' ',
' ',
' ',
' ',
' ',
'[removed]',
'[removed]',
'[removed]',
'[removed]',
'[removed]',
'[removed]',
'[removed]',
'[removed]',
'[removed]',
'[removed]',
'[removed]',
'[removed]',
'[removed]',
'[removed]',
'[removed]',
'[removed]',
'[removed]',
'[removed]',
'[removed]',
'[removed]',
'[removed]',
'[removed]',
'[removed]',
'[removed]',
'[removed]',
'[removed]',
'[removed]',
'[removed]',
'[removed]',
'[removed]',
'[removed]',
'[removed]',
'[removed]',
'[removed]',
'[removed]',
'[removed]',
'[removed]',
'[removed]',
'[removed]',
'[removed]',
'[removed]',
'[removed]'
);

// REPLACE EACH PART WITH A <IMG> POINTING TOWARDS AN IMAGE WITH THE SIZE OF AT LEAST 40X40PX (BEST IF ~20X20PX)

?>
